const BIRTHDAY_PROFILES_KEY = 'BIRTHDAY_PROFILES';

const BIRTHDAY_PROFILE_BY_ID_KEY = 'BIRTHDAY_PROFILE_BY_ID';

const AUTHORIZED_MY_DETAILS_KEY = 'AUTHORIZED_MY_DETAILS';

const TIME_ZONES_KEY = 'TIME_ZONE';

export {
  BIRTHDAY_PROFILES_KEY,
  BIRTHDAY_PROFILE_BY_ID_KEY,
  AUTHORIZED_MY_DETAILS_KEY,
  TIME_ZONES_KEY,
};
